import type { TextContent } from './types';

// API keys are now SERVER-SIDE ONLY (process.env.GEMINI_API_KEY in /api/gemini).
// This array must stay EMPTY — anything here is bundled into the public browser JS.
export const BACKUP_API_KEYS: string[] = [];

export const WHATSAPP_SUPPORT_LINK = "https://wa.me/message/VJDW3IISAWAPM1";

// Support link with a friendly pre-filled message (carries the user's A6 id).
export function buildSupportLink(id?: string | null, isFR: boolean = true): string {
  const msg = isFR
    ? `Bonjour 👋, mon ID est ${id || "—"}. J'ai besoin d'assistance pour : `
    : `Hi 👋, my ID is ${id || "—"}. I need help with: `;
  return `${WHATSAPP_SUPPORT_LINK}?text=${encodeURIComponent(msg)}`;
}

export const textContent: TextContent = {
  en: {
    lang: 'en',
    headerTitle: 'a6ko',
    controlsTitle: 'Photoshoot Studio',
    watchTutorial: 'Watch tutorial',
    model: 'Human Subject',
    changeModel: 'Upload Subject Photo',
    chooseYourModel: 'Choose Subject Photo',
    yourUploadedModels: 'Your History',
    presetModels: 'Presets',
    generateYourOwn: 'Create with AI',
    uploadAPhoto: 'Upload Biometric Photo',
    uploadModelGuidance: 'For the best results, use a clear portrait with a direct gaze.',
    fullBodyPhoto: 'Full Body Photo (Optional)',
    uploadFullBody: 'Upload Full Body',
    bodyDescription: 'Height & Build',
    bodyDescriptionPlaceholder: 'Describe height/weight (e.g. 1m85, athletic)',
    fullPhotoReady: 'Full Photo Ready',
    orCreateWithAI: 'OR GENERATE PERSON',
    generateModelPromptPlaceholder: 'e.g., a man with short dreadlocks...',
    generateModel: 'Generate Subject',
    generatingModel: 'Creating subject...',
    failedToGenerateModel: 'Failed to generate subject.',
    failedToUploadModel: 'Failed to upload photo.',
    select: 'Use This Photo',
    selected: 'Selected',
    uploading: 'Uploading...',
    close: 'Close',
    tattoos: 'Body Art / Tattoos',
    tattoos_none: 'None',
    tattoos_minimal: 'Minimal',
    tattoos_symbols: 'Symbols',
    tattoos_discreet: 'Discreet',
    tattoos_full: 'Full Canvas',
    recentModels: 'Recent Subjects',
    recentGarments: 'Recent Garments',
    garment: 'Garment Specification',
    garmentDescription: 'Describe the Clothing',
    garmentDescriptionPlaceholder: 'Describe what you want to wear here or click on the button below to upload your clothes (without a face recommended)',
    uploadGarment: 'Use Garment Photo',
    analyzingGarment: 'Analyzing fabric...',
    companion: 'Guest Person',
    enableCompanion: 'Add a Guest to Scene',
    companionDescription: 'Guest Description',
    companionDescriptionPlaceholder: 'e.g., A handsome man in a black tuxedo...',
    uploadCompanion: 'Upload Guest Photo',
    photoSelected: 'Photo Ready',
    removePhoto: 'Remove',
    uploadPhoto: 'Upload Photo',
    accessories: 'Accessories',
    shoes: 'Shoes',
    shoesPlaceholder: 'e.g. Christian Louboutin red bottoms',
    watch: 'Watch',
    watchPlaceholder: 'e.g. Rolex Submariner',
    jewelry: 'Jewelry',
    jewelryPlaceholder: 'e.g. Cartier Love bracelet, diamond necklace',
    otherAccessories: 'Other Accessories',
    otherAccessoriesPlaceholder: 'e.g. Gucci sunglasses, Hermes Birkin bag',
    scene: 'Scene & Composition',
    pose: 'Pose',
    runway: 'Runway Stride',
    editorial: 'Editorial Vogue',
    portrait: 'High-Fashion Portrait',
    dynamicPose: 'Motion / Action',
    candid: 'Natural / Candid',
    productFocus: 'Product-Led',
    sittingPose: 'Seated Pose',
    gesture: 'Hand Gestures',
    selfiePose: 'Smartphone Selfie',
    mode: 'Street Style / Mode',
    glamour: 'Pure Glamour',
    corporate: 'Corporate / Luxury Office',
    smoking: 'Smoking',
    classyBusiness: 'Classy Business',
    eliteSmoking: 'Elite Smoking',
    blackAndWhite: 'Black and White',
    eliteCigarBlackAndWhite: 'Elite Cigar Black & White',
    environment: 'Environment',
    randomizeEnvironment: 'Shuffle Environment',
    studio: 'Studio (Minimal)',
    outdoor: 'Outdoor / Natural',
    urbanRooftop: 'Urban Skyline Rooftop',
    desertOasis: 'Golden Desert Oasis',
    botanicalGarden: 'Lush Botanical Garden',
    baroqueGrandeur: 'Baroque Palace',
    minimalistArtGallery: 'Art Gallery',
    neonCityscape: 'Cyberpunk Neon',
    virtualParade: 'Virtual Parade',
    insidePrivateJet: 'Private Jet Interior',
    corporateOffice: 'Executive Suite',
    redCarpet: 'Met Gala Red Carpet',
    christmasSpecial: 'Festive Christmas',
    newYearGala: 'New Year Gala',
    valentinesDay: 'Romantic Valentine\'s Decor',
    birthdayParty: 'Luxury Birthday Gala',
    '5StarsHotelSuite': '5 Stars Hotel Suite',
    HotelInteriorSuite: 'Hotel Interior Suite',
    // Intent Options
    intent_mode: 'Fashion (Mode)',
    intent_ecommerce: 'E-commerce',
    intent_lookbook: 'Lookbook',
    intent_editorial: 'Editorial',
    intent_social: 'Social Media',
    intent_corporate: 'Corporate',
    intent: 'Intent',
    // Camera Angle Options
    angle_eye: 'Eye Level',
    angle_low: 'Low Angle',
    angle_waist: 'Waist Level',
    angle_chest: 'Chest Level',
    angle_high: 'High Angle',
    angle_overhead: 'Overhead',
    cameraAngle: 'Camera Angle',
    // Camera Axis Options
    axis_front: 'Front',
    axis_threeQuarter: '3/4 View',
    axis_profile: 'Profile',
    axis_back: 'Back',
    keynote_axis_front: 'From Audience (Faces Camera)',
    keynote_axis_threeQuarter: 'Stage Diagonal (Faces Audience)',
    keynote_axis_profile: 'Side Stage (Faces Audience)',
    keynote_axis_back: 'Behind Speaker (Shows Audience)',
    cameraAxis: 'Camera Axis',
    // Camera Distance Options
    dist_closeup: 'Close-up (Face)',
    dist_waist: 'Waist Up',
    dist_full: 'Full Body',
    dist_wide: 'Wide Shot',
    cameraDistance: 'Camera Distance',
    // Camera Lens Options
    lens_35mm: '35mm (Reportage)',
    lens_50mm: '50mm (Natural)',
    lens_85mm: '85mm (Portrait/Bokeh)',
    lens_200mm: '200mm (Compression)',
    cameraLens: 'Lens Simulation',
    cameraSettings: 'Camera & Lens',
    // Background Type Options
    bg_solid: 'Solid Color',
    bg_textured: 'Textured',
    bg_artistic: 'Artistic Painted',
    bg_cyclorama: 'Cyclorama',
    backgroundType: 'Background Type',
    // Environment Options
    env_studio: 'Studio (Minimal)',
    env_africanArch: 'African Architecture',
    env_africanNature: 'African Nature',
    env_africanUrban: 'African Urban',
    env_localLuxury: 'Local Luxury',
    env_runway: 'Runway',
    env_outdoor: 'Outdoor / Natural',
    env_desertOasis: 'Golden Desert Oasis',
    env_conferenceRoom: 'On stage as Keynote speaker',
    env_podcastStudio: 'Podcast studio',
    env_memeSetting: 'Meme setting',
    micType: 'Microphone Type',
    mic_podium: 'Podium Gooseneck',
    mic_headset: 'Discreet Headset',
    mic_handheld: 'Handheld',
    mic_none: 'None',
    audienceView: 'Audience View',
    aud_blurred: 'Blurred Background',
    aud_grandPlan: 'Grand Plan (Wide Shot)',
    aud_silhouette: 'Silhouette Foreground',
    aud_none: 'None',
    additionalPrompt: 'Custom Instruction',
    additionalPromptPlaceholder: 'Add any extra details for the scene or environment...',
    // Color Palette Options
    palette_neutral: 'Neutral',
    palette_earthy: 'Earthy',
    palette_vibrant: 'Vibrant',
    palette_monochrome: 'Monochrome',
    palette_pastel: 'Pastel',
    palette_dark: 'Dark & Moody',
    colorPalette: 'Color Palette',
    // Lighting Setup Options
    light_rembrandt: 'Rembrandt',
    light_butterfly: 'Butterfly/Paramount',
    light_split: 'Split',
    light_loop: 'Loop',
    light_broad: 'Broad',
    light_short: 'Short',
    light_flat: 'Flat',
    light_overhead: 'Softbox Overhead',
    lighting: 'Lighting Rig',
    // Lighting Temperature Options
    temp_warm: 'Warm (3200K)',
    temp_neutral: 'Neutral (5500K)',
    temp_cool: 'Cool (7000K)',
    lightingTemperature: 'Color Temperature',
    // Lighting Time Options
    time_golden: 'Golden Hour',
    time_midday: 'Harsh Midday',
    time_night: 'Night Flash',
    lightingTime: 'Time of Day / Env',
    // Lighting Mood Options
    mood_clinical: 'Clinical & Sharp',
    mood_dramatic: 'Dramatic',
    mood_soft: 'Soft & Flattering',
    lightingMood: 'Overall Mood',
    // Film Grain Options
    grain_analog: 'Analog Film',
    grain_digital: 'Crisp Digital',
    grain_hdr: 'HDR',
    filmGrain: 'Film Grain/Texture',
    // Post Processing Options
    post_vibrant: 'Vibrant Colors',
    post_desaturated: 'Desaturated',
    post_monochrome: 'Monochrome',
    postProcessing: 'Post-Processing Style',
    postProcessingTitle: 'Finishing & Post',
    output: 'Production Settings',
    variants: 'Number of Shots',
    aspectRatio: 'Frame Ratio',
    watermark: 'Watermark',
    watermarkDesc: 'Display "Studio a6ko" watermark',
    bwMode: 'Black & White Mode',
    bwModeDesc: 'Force pure grayscale photo output',
    generate: 'Launch Photoshoot',
    generating: 'Processing masterpiece...',
    galleryWelcomeTitle: 'Your Portfolio',
    galleryWelcomeMessage: 'Configure your studio settings and click "Launch Photoshoot" to see the magic.',
    errorTitle: 'Studio Error',
    animationErrorTitle: 'Animation Error',
    quotaExceededMessage: 'All servers are currently busy. Please try again in a few minutes.',
    refreshPage: 'Refresh Studio',
    contactSupport: 'Contact Support',
    download: 'Export',
    downloadPNG: 'Export 4K PNG',
    downloadMP4: 'Export 4K MP4',
    prompt: 'Technical Prompt',
    dominantColors: 'Color Palette',
    inspireMe: 'Inspire Me',
    selectAVariation: 'Choose Variation',
    regenerate: 'Reshoot',
    resetToImage: 'Back to Still',
    like: 'Premium',
    dislike: 'Discard',
    editImage: 'Magic Edit',
    editing: 'Editing...',
    describeChanges: 'e.g., "Add designer sunglasses", "Change hair to blonde"',
    applyEdit: 'Apply Changes',
    cancel: 'Discard',
    animate: 'Animate (Veo 3.1)',
    animating: 'Rendering...',
    animationSettings: 'Motion Director',
    animationDuration: 'Clip Duration',
    animationCameraMove: 'Camera Path',
    cameraMoveNone: 'Fixed Lens',
    cameraMovePan: 'Cinematic Pan',
    cameraMoveZoom: 'Dolly Zoom',
    cameraMoveDolly: 'Dolly Forward',
    animationStyle: 'Frame Speed',
    styleNormal: '24 FPS',
    styleSlowMo: 'Slow Motion',
    styleFastForward: 'Fast Forward',
    audioType: 'Audio Selection',
    audioNone: 'Silent',
    audioMusic: 'Ambient Music',
    audioScript: 'Voice AI Script',
    musicStyle: 'Track Style',
    musicUplifting: 'Uplifting Electronic',
    musicLofi: 'Lofi Chill',
    musicCinematic: 'Cinematic',
    musicTribal: 'Afro Beats / Tribal',
    voiceoverScript: 'AI Voiceover Text',
    voiceoverScriptPlaceholder: 'Enter script for the AI person to speak...',
    failedToGenerateScript: 'Failed to generate a new script idea. Please try again.',
    voiceGender: 'Speaker Gender',
    voiceAuto: 'Auto-Select',
    voiceFemale: 'Female AI',
    voiceMale: 'Male AI',
    defaultVoiceoverScript: 'Hello, I am an AI person generated by Studio a6ko. Create your fashion portfolio today.',
    generateAnimation: 'Render 4K Video',
    generatedPrompt: 'Metadata Manifest',
    copy: 'Copy',
    copied: 'Copied!',
    credits: 'Remaining Credits',
    needMoreCredits: 'Recharge Credits',
    buyCredits: 'Get More Credits',
    paywallMessage: 'Unlock full 4K production and high-fidelity video rendering.',
    paywallOffer: 'Premium Pack: 2999 XOF',
    paywallBenefits: [
        '✨ 25 Premium Production Credits',
        '📸 Ultra-HD 4K Still Shots',
        '🎥 4K Video Animation Access',
        '⚡ High-Priority Server Access',
        '🛠️ Professional Editing Tools'
    ],
    paywallSubtext: 'Refill your creative engine.',
    buyNow: 'Purchase Pack',
    paymentInstructions: 'Secure payment. Credits added instantly.',
    paymentSuccessTitle: 'Production Ready!',
    paymentSuccessMessage: 'Your credits have been successfully added.',
    continueCreating: 'Resume Photoshoot',
    animationPremiumOnly: 'Video rendering is a premium feature.',
    verifyPayment: 'Verification',
    uploadScreenshot: 'Upload Receipt',
    verifying: 'Verifying...',
    verificationFailed: 'Verification Issue',
    verificationSuccess: 'Account Refilled!',
    manualSupportCode: 'Have a VIP Code?',
    enterCodePlaceholder: 'A6KO-XXXX-XXXX',
    apply: 'Activate',
    invalidCode: 'Code not recognized.',
    yourUserId: 'Director ID',
    pleaseSendId: 'Contact support with your ID if you face issues.',
    copyId: 'Copy ID',
    // Landing Page
    landingTitle: 'Studio',
    landingTitleSuffix: 'Photoshoot',
    landingSubtitle: 'Create professional, ultra-realistic fashion photography with your own photos. Save over 50,000 CFA on professional shoots.',
    launchStudio: 'Launch Studio',
    featuresAIModelsTitle: 'Professional Photoshoot',
    featuresAIModelsDesc: 'Upload your real photo and get professional studio results instantly.',
    featuresGarmentsTitle: 'Custom Garments',
    featuresGarmentsDesc: 'Describe any outfit and see it draped perfectly with realistic fabric physics.',
    featuresVideoTitle: '4K Video',
    featuresVideoDesc: 'Animate your photos into stunning 4K cinematic videos with camera motion.',
    navHome: 'Home',
    navTryOn: 'Virtual Try-On',
    navPhotoshoot: 'Photoshooting Studio',
    navCreatives: 'Creatives Studio',
    navAccount: 'User Account',
    navInspiration: 'Inspiration Gallery',
    creditsLabel: 'Credits',
    // Creatives Studio
    creativesTitle: 'Creatives Studio',
    creativesSubtitle: 'Generate professional ad designs and marketing creatives directly from your inputs.',
    comingSoon: 'Coming Soon',
    adGeneratorPlaceholder: 'Ad Generator Preview Placeholder',
    // Home Landing Page
    homeLiveBadge: 'Studio a6ko is now live',
    homeHeroTitle1: 'The AI-Powered',
    homeHeroTitle2: 'Creative Engine',
    homeHeroSubtitle: 'Generate hyper-realistic fashion photos, design brand identities, and create high-converting ad creatives in seconds.',
    homePhotoshootTitle: 'Virtual Photoshoot Studio',
    homePhotoshootDesc: 'Upload your garments and generate hyper-realistic fashion photos in diverse environments, lighting, and poses.',
    homeCreativesTitle: 'Ad Creative Studio',
    homeCreativesDesc: 'Design logos, pitch decks, social media graphics, and marketing assets tailored to your brand identity.',
    homeWhyChooseTitle: 'Why choose Studio a6ko?',
    homeWhyChooseSubtitle: 'Replace expensive agencies, long wait times, and complex software with instant, AI-generated perfection.',
    homeFeature1Title: 'Lightning Fast',
    homeFeature1Desc: 'Go from concept to final asset in seconds. No more waiting weeks for photoshoots or design revisions.',
    homeFeature2Title: 'Cost-Effective',
    homeFeature2Desc: 'Eliminate the need for expensive photoshoots, photographers, studios, and high-priced creative agencies.',
    homeFeature3Title: 'Hyper-Local & Global',
    homeFeature3Desc: 'Generate diverse people and culturally relevant designs tailored to any market or demographic instantly.',
    homeDeepDivePhotoshootTag: 'Virtual Photoshoot',
    homeDeepDivePhotoshootTitle1: 'Your garments on',
    homeDeepDivePhotoshootTitle2: 'hyper-realistic people',
    homeDeepDivePhotoshootDesc: 'Stop paying for expensive studio time. Upload a flat-lay of your clothing and let our AI drape it naturally on diverse people in any setting, lighting, or pose.',
    homeDeepDivePhotoshootList1: 'Upload flat-lays or garment photos',
    homeDeepDivePhotoshootList2: 'Select person ethnicity, age, and body type',
    homeDeepDivePhotoshootList3: 'Choose studio lighting or outdoor environments',
    homeDeepDivePhotoshootList4: 'Generate 4K, e-commerce ready images',
    homeDeepDivePhotoshootCTA: 'Try Photoshoot Studio',
    homeDeepDiveCreativesTag: 'Ad Creative Studio',
    homeDeepDiveCreativesTitle1: 'Generate',
    homeDeepDiveCreativesTitle2: 'high-converting assets',
    homeDeepDiveCreativesDesc: 'From foundational brand identity to performance marketing. Tailor every asset to your target audience, emotional trigger, and core value proposition.',
    homeTab1Title: 'Brand Identity',
    homeTab1Desc: 'Logos, guidelines, and core assets.',
    homeTab2Title: 'Digital Marketing',
    homeTab2Desc: 'Social media, email, and web ads.',
    homeTab3Title: 'Sales & Pitch',
    homeTab3Desc: 'Presentations and investor decks.',
    homeDeepDiveCreativesCTA: 'Try Ad Creative Studio',
    homeFinalCTATitle: 'Ready to transform your brand?',
    homeFinalCTASubtitle: 'Join thousands of creators, agencies, and brands using Studio a6ko to scale their creative output.',
    homeFinalCTAPhotoshoot: 'Start Photoshoot',
    homeFinalCTACreatives: 'Design Creatives',
    // Creatives Landing Page
    creativesLandingTitle: 'What do you need to create today?',
    creativesLandingSubtitle: 'Select a creative category below to launch the personalized AI studio.',
    creativesCat1Title: 'Fundamental Brand Identity',
    creativesCat2Title: 'Digital Presence & Marketing',
    creativesCat3Title: 'Print & Physical Assets',
    creativesCat4Title: 'Sales & Communication',
    creativesCat1Item1: 'Logo Design',
    creativesCat1Item2: 'Brand Guidelines (Style Guide)',
    creativesCat1Item3: 'Brand Assets',
    creativesCat2Item1: 'Website Design (UI/UX)',
    creativesCat2Item2: 'Social Media Graphics',
    creativesCat2Item3: 'Email Marketing Templates',
    creativesCat2Item4: 'Digital Advertisements',
    creativesCat3Item1: 'Business Cards & Stationery',
    creativesCat3Item2: 'Packaging Design',
    creativesCat3Item3: 'Brochures & Flyers',
    creativesCat4Item1: 'Pitch Decks & Presentations',
    creativesCat4Item2: 'Sales Collateral',
    creativesCat4Item3: 'Music release assets',
    creativesCat1Item1Desc: 'A unique, memorable logo is the foundation of brand recognition.',
    creativesCat1Item2Desc: 'A document ensuring consistent colors, fonts, and brand voice across all platforms.',
    creativesCat1Item3Desc: 'Curated imagery, icons, and, if necessary, custom illustrations.',
    creativesCat2Item1Desc: 'A responsive website that acts as the hub for customer engagement.',
    creativesCat2Item2Desc: 'Templates for posts, stories, and banners to maintain a consistent aesthetic.',
    creativesCat2Item3Desc: 'Branded layouts for newsletters and promotional emails.',
    creativesCat2Item4Desc: 'Compelling imagery for Google Ads, social media ads, and banner ads.',
    creativesCat3Item1Desc: 'Professional, tangible branded materials for networking.',
    creativesCat3Item2Desc: 'Crucial for attracting customers on shelves.',
    creativesCat3Item3Desc: 'Brochures, flyers, and banners for physical locations or events.',
    creativesCat4Item1Desc: 'Visually engaging slides for proposals, investor pitches, or client meetings.',
    creativesCat4Item2Desc: 'Designed documents that make data easy to understand.',
    creativesCat4Item3Desc: 'Assets for music releases.',
    creativesStudioTitle: 'Ad Creative Studio',
    creativesStudioDesc: 'Generate high-performing visual ads.',
    yourCreativesTitle: 'Your Creatives',
    yourCreativesDesc: 'Fill out the required inputs on the left and click "Generate Ad Creative" to see the magic.',
    generateAdCreative: 'Generate Ad Creative',
    costCredit: 'Cost: {cost} Credit',
    balance: 'Balance: {credits}',
    verifyingIdentity: 'Verifying Identity...',
    photoReady: 'Photo Ready',
    apiKeyRequiredTitle: 'Video Generation Requires API Key',
    apiKeyRequiredDesc: 'To create animations, this application uses Google\'s powerful Veo models. You\'ll need to select a Google AI API key from a project that has billing enabled to continue.',
    selectApiKey: 'Select API Key',
    apiKeyDisclaimer: 'Your API key is used directly and is not stored by this application. For more information on billing, please visit',
    marketingCopy: 'Marketing Copy',
    satisfaction: 'Satisfaction',
    // User Account
    accountTitle: 'User Account',
    directorId: 'Director ID',
    availableCredits: 'Available Credits',
    needHelp: 'Need help? Contact support with your Director ID.',
    whatsappShareMessage: "Try your models for free with Studio A6ko 📸✨\n",
    loginTitle: 'Connect to Studio',
    loginSubtitle: 'Authentication is required to secure your visual workspace and protect your creation credits.',
    continueWithGoogle: 'Continue with Google',
    loginSecurePromise: 'Zero Farming Policy: To guarantee server stability and ensure fair allocation of resource streams, we require verified social accounts.',
    signOut: 'Sign Out',
  },
  fr: {
    lang: 'fr',
    headerTitle: 'a6ko',
    controlsTitle: 'Studio de Séance Photo',
    watchTutorial: 'Voir le tutoriel',
    model: 'Sujet Humain',
    changeModel: 'Télécharger la Photo du Sujet',
    chooseYourModel: 'Choisissez la Photo du Sujet',
    yourUploadedModels: 'Votre Historique',
    presetModels: 'Préréglages',
    generateYourOwn: 'Créer avec l\'IA',
    uploadAPhoto: 'Photo Biométrique',
    uploadModelGuidance: 'Pour un meilleur rendu, utilisez un portrait clair avec un regard direct.',
    fullBodyPhoto: 'Photo Entière (Optionnelle)',
    uploadFullBody: 'Uploader Photo Entière',
    bodyDescription: 'Taille et corpulence',
    bodyDescriptionPlaceholder: 'Précisez taille/poids (ex: 1m85, athlétique)',
    fullPhotoReady: 'Photo Entière Prête',
    orCreateWithAI: 'OU GÉNÉRER UNE PERSONNE',
    generateModelPromptPlaceholder: 'ex: un homme avec de courtes dreadlocks...',
    generateModel: 'Générer le Sujet',
    generatingModel: 'Création du sujet...',
    failedToGenerateModel: 'Échec de la génération.',
    failedToUploadModel: 'Échec du téléchargement.',
    select: 'Utiliser cette Photo',
    selected: 'Sélectionné',
    uploading: 'Chargement...',
    close: 'Fermer',
    tattoos: 'Art Corporel / Tatouages',
    tattoos_none: 'Aucun',
    tattoos_minimal: 'Minimaliste',
    tattoos_symbols: 'Symboles',
    tattoos_discreet: 'Discret',
    tattoos_full: 'Toile Complète',
    recentModels: 'Sujets Récents',
    recentGarments: 'Vêtements Récents',
    garment: 'Spécification du Vêtement',
    garmentDescription: 'Décrire le Vêtement',
    garmentDescriptionPlaceholder: 'Décrivez ce que vous voulez porter ici ou cliquez sur le bouton ci-dessous pour télécharger vos vêtements (sans visage recommandé)',
    uploadGarment: 'Photo du Vêtement',
    analyzingGarment: 'Analyse du tissu...',
    companion: 'Personne Invitée',
    enableCompanion: 'Ajouter un invité à la scène',
    companionDescription: 'Description de l\'invité',
    companionDescriptionPlaceholder: 'ex: Un homme élégant en smoking noir...',
    uploadCompanion: 'Photo de l\'invité',
    photoSelected: 'Photo Prête',
    removePhoto: 'Supprimer',
    uploadPhoto: 'Télécharger',
    accessories: 'Accessoires',
    shoes: 'Chaussures',
    shoesPlaceholder: 'ex: Christian Louboutin semelles rouges',
    watch: 'Montre',
    watchPlaceholder: 'ex: Rolex Submariner',
    jewelry: 'Bijoux',
    jewelryPlaceholder: 'ex: Bracelet Cartier Love, collier de diamants',
    otherAccessories: 'Autres Accessoires',
    otherAccessoriesPlaceholder: 'ex: Lunettes Gucci, sac Hermes Birkin',
    scene: 'Scène & Composition',
    pose: 'Pose',
    runway: 'Défilé de Mode',
    editorial: 'Éditorial Vogue',
    portrait: 'Portrait Haute Couture',
    dynamicPose: 'Mouvement / Action',
    candid: 'Naturel / Instantané',
    productFocus: 'Focus Produit',
    sittingPose: 'Pose Assise',
    gesture: 'Gestuelle des mains',
    selfiePose: 'Selfie Smartphone',
    mode: 'Style Urbain / Mode',
    glamour: 'Pur Glamour',
    corporate: 'Bureau de Luxe',
    smoking: 'Fumeur',
    classyBusiness: 'Business Classe',
    eliteSmoking: 'Fumeur Élite',
    environment: 'Environnement',
    randomizeEnvironment: 'Mélanger l\'Environnement',
    studio: 'Studio (Minimaliste)',
    outdoor: 'Extérieur / Naturel',
    urbanRooftop: 'Toit avec Vue Urbaine',
    desertOasis: 'Oasis dans le Désert',
    botanicalGarden: 'Jardin Botanique Luxe',
    baroqueGrandeur: 'Palais Baroque',
    minimalistArtGallery: 'Galerie d\'Art',
    neonCityscape: 'Ville Néon Cyberpunk',
    virtualParade: 'Défilé Virtuel',
    insidePrivateJet: 'Intérieur de Jet Privé',
    corporateOffice: 'Suite Executive',
    redCarpet: 'Tapis Rouge Met Gala',
    christmasSpecial: 'Spécial Noël',
    newYearGala: 'Gala du Nouvel An',
    valentinesDay: 'Décor Romantique Valentin',
    birthdayParty: 'Gala d\'Anniversaire Luxe',
    '5StarsHotelSuite': 'Suite Hôtel 5 Étoiles',
    HotelInteriorSuite: 'Intérieur Suite Hôtel',
    // Intent Options
    intent_mode: 'Mode (Fashion)',
    intent_ecommerce: 'E-commerce',
    intent_lookbook: 'Lookbook',
    intent_editorial: 'Éditorial',
    intent_social: 'Réseaux Sociaux',
    intent_corporate: 'Entreprise',
    intent: 'Intention',
    // Camera Angle Options
    angle_eye: 'Niveau des Yeux',
    angle_low: 'Angle Faible',
    angle_waist: 'Niveau de la Taille',
    angle_chest: 'Niveau de la Poitrine',
    angle_high: 'Angle Élevé',
    angle_overhead: 'Zénithal',
    cameraAngle: 'Angle de Caméra',
    // Camera Axis Options
    axis_front: 'Face',
    axis_threeQuarter: 'Vue 3/4',
    axis_profile: 'Profil',
    axis_back: 'Dos',
    keynote_axis_front: 'Depuis le public (Face Caméra)',
    keynote_axis_threeQuarter: 'Diagonale Scène (Face Public)',
    keynote_axis_profile: 'Côté Scène (Face Public)',
    keynote_axis_back: 'Derrière l\'orateur (Montre Public)',
    cameraAxis: 'Axe de Caméra',
    // Camera Distance Options
    dist_closeup: 'Gros Plan (Visage)',
    dist_waist: 'Taille Haute',
    dist_full: 'Corps Entier',
    dist_wide: 'Plan Large',
    cameraDistance: 'Distance de Caméra',
    // Camera Lens Options
    lens_35mm: '35mm (Reportage)',
    lens_50mm: '50mm (Naturel)',
    lens_85mm: '85mm (Portrait/Bokeh)',
    lens_200mm: '200mm (Compression)',
    cameraLens: 'Simulation d\'Objectif',
    cameraSettings: 'Caméra & Objectif',
    // Background Type Options
    bg_solid: 'Couleur Unie',
    bg_textured: 'Texturé',
    bg_artistic: 'Peint Artistique',
    bg_cyclorama: 'Cyclorama',
    backgroundType: 'Type d\'Arrière-plan',
    // Environment Options
    env_studio: 'Studio (Minimaliste)',
    env_africanArch: 'Architecture Africaine',
    env_africanNature: 'Nature Africaine',
    env_africanUrban: 'Urbain Africain',
    env_localLuxury: 'Luxe Local',
    env_runway: 'Défilé',
    env_outdoor: 'Extérieur / Naturel',
    env_desertOasis: 'Oasis du Désert Doré',
    env_conferenceRoom: 'Sur scène en tant que conférencier',
    env_podcastStudio: 'Studio de podcast',
    env_memeSetting: 'Décor de mème',
    micType: 'Type de Microphone',
    mic_podium: 'Col de cygne sur pupitre',
    mic_headset: 'Micro-casque discret',
    mic_handheld: 'Micro main',
    mic_none: 'Aucun',
    audienceView: 'Vue du Public',
    aud_blurred: 'Arrière-plan flou',
    aud_grandPlan: 'Grand Plan (Plan Large)',
    aud_silhouette: 'Premier plan en silhouette',
    aud_none: 'Aucun',
    additionalPrompt: 'Instruction Personnalisée',
    additionalPromptPlaceholder: 'Ajoutez des détails supplémentaires pour la scène ou l\'environnement...',
    // Color Palette Options
    palette_neutral: 'Neutre',
    palette_earthy: 'Terreux',
    palette_vibrant: 'Vibrant',
    palette_monochrome: 'Monochrome',
    palette_pastel: 'Pastel',
    palette_dark: 'Sombre & Mystérieux',
    colorPalette: 'Palette de Couleurs',
    // Lighting Setup Options
    light_rembrandt: 'Rembrandt',
    light_butterfly: 'Papillon/Paramount',
    light_split: 'Divisé',
    light_loop: 'Boucle',
    light_broad: 'Large',
    light_short: 'Court',
    light_flat: 'Plat',
    light_overhead: 'Softbox Zénithal',
    lighting: 'Dispositif d\'Éclairage',
    // Lighting Temperature Options
    temp_warm: 'Chaud (3200K)',
    temp_neutral: 'Neutre (5500K)',
    temp_cool: 'Froid (7000K)',
    lightingTemperature: 'Température de Couleur',
    // Lighting Time Options
    time_golden: 'Heure Dorée',
    time_midday: 'Midi Intense',
    time_night: 'Flash de Nuit',
    lightingTime: 'Moment de la Journée / Env',
    // Lighting Mood Options
    mood_clinical: 'Clinique & Précis',
    mood_dramatic: 'Dramatique',
    mood_soft: 'Doux & Flatteur',
    lightingMood: 'Ambiance Générale',
    // Film Grain Options
    grain_analog: 'Film Analogique',
    grain_digital: 'Numérique Net',
    grain_hdr: 'HDR',
    filmGrain: 'Grain de Pellicule / Texture',
    // Post Processing Options
    post_vibrant: 'Couleurs Vibrantes',
    post_desaturated: 'Désaturé',
    post_monochrome: 'Monochrome',
    postProcessing: 'Style de Post-Traitement',
    postProcessingTitle: 'Finition & Post-Production',
    output: 'Paramètres de Production',
    variants: 'Nombre de Clichés',
    aspectRatio: 'Format d\'Image',
    watermark: 'Filigrane',
    watermarkDesc: 'Afficher le filigrane "Studio a6ko"',
    bwMode: 'Mode Noir & Blanc',
    bwModeDesc: 'Forcer la sortie en niveaux de gris purs',
    generate: 'Lancer le Shoot',
    generating: 'Création du chef-d\'œuvre...',
    galleryWelcomeTitle: 'Votre Portfolio',
    galleryWelcomeMessage: 'Configurez vos réglages studio et cliquez sur "Lancer le Shoot" pour voir la magie.',
    errorTitle: 'Erreur Studio',
    animationErrorTitle: 'Erreur d\'Animation',
    quotaExceededMessage: 'Tous les serveurs sont actuellement occupés. Veuillez réessayer dans quelques minutes.',
    refreshPage: 'Actualiser le Studio',
    contactSupport: 'Contacter le Support',
    download: 'Exporter',
    downloadPNG: 'Exporter PNG 4K',
    downloadMP4: 'Exporter MP4 4K',
    prompt: 'Prompt Technique',
    dominantColors: 'Palette de Couleurs',
    inspireMe: 'Inspirez-moi',
    selectAVariation: 'Choisir une Variation',
    regenerate: 'Refaire le Shoot',
    resetToImage: 'Retour à l\'Image',
    like: 'Premium',
    dislike: 'Rejeter',
    editImage: 'Magic Edit',
    editing: 'Édition...',
    describeChanges: 'ex: "Ajouter des lunettes de soleil designer"',
    applyEdit: 'Appliquer',
    cancel: 'Annuler',
    animate: 'Animer (Veo 3.1)',
    animating: 'Rendu...',
    animationSettings: 'Direction du Mouvement',
    animationDuration: 'Durée du Clip',
    animationCameraMove: 'Chemin Caméra',
    cameraMoveNone: 'Lentille Fixe',
    cameraMovePan: 'Panoramique Ciné',
    cameraMoveZoom: 'Dolly Zoom',
    cameraMoveDolly: 'Travelling Avant',
    animationStyle: 'Vitesse de Frame',
    styleNormal: '24 FPS',
    styleSlowMo: 'Ralenti',
    styleFastForward: 'Avance Rapide',
    audioType: 'Sélection Audio',
    audioNone: 'Silencieux',
    audioMusic: 'Musique d\'Ambiance',
    audioScript: 'Script Voix IA',
    musicStyle: 'Style de Piste',
    musicUplifting: 'Électronique Inspirant',
    musicLofi: 'Lofi Chill',
    musicCinematic: 'Cinématographique',
    musicTribal: 'Afro Beats / Tribal',
    voiceoverScript: 'Texte Voix IA',
    voiceoverScriptPlaceholder: 'Entrez le texte à dire...',
    failedToGenerateScript: 'Échec de la génération d\'une nouvelle idée de script. Veuillez réessayer.',
    voiceGender: 'Genre Voix',
    voiceAuto: 'Auto-Sélect',
    voiceFemale: 'Femme IA',
    voiceMale: 'Homme IA',
    defaultVoiceoverScript: 'Bonjour, je suis un modèle IA généré par Studio a6ko. Créez votre portfolio aujourd\'hui.',
    generateAnimation: 'Rendre Vidéo 4K',
    generatedPrompt: 'Manifeste Métadonnées',
    copy: 'Copier',
    copied: 'Copié !',
    credits: 'Crédit Restant',
    needMoreCredits: 'Recharger Crédits',
    buyCredits: 'Plus de Crédits',
    paywallMessage: 'Débloquez la production 4K complète et le rendu vidéo haute-fidélité.',
    paywallOffer: 'Pack Premium : 2999 XOF',
    paywallBenefits: [
        '✨ 25 Crédits de Production Premium',
        '📸 Photos Ultra-HD 4K',
        '🎥 Accès Animation Vidéo 4K',
        '⚡ Accès Serveur Prioritaire',
        '🛠️ Outils d\'Édition Professionnels'
    ],
    paywallSubtext: 'Rechargez votre moteur créatif.',
    buyNow: 'Acheter Pack',
    paymentInstructions: 'Paiement sécurisé. Crédits ajoutés instantanément.',
    paymentSuccessTitle: 'Prêt pour la Production !',
    paymentSuccessMessage: 'Vos crédits ont été ajoutés avec succès.',
    continueCreating: 'Reprendre le Shoot',
    animationPremiumOnly: 'Le rendu vidéo est une fonction premium.',
    verifyPayment: 'Vérification',
    uploadScreenshot: 'Télécharger Reçu',
    verifying: 'Vérification...',
    verificationFailed: 'Problème de Vérification',
    verificationSuccess: 'Compte Rechargé !',
    manualSupportCode: 'Code VIP ?',
    enterCodePlaceholder: 'A6KO-XXXX-XXXX',
    apply: 'Activer',
    invalidCode: 'Code non reconnu.',
    yourUserId: 'ID Directeur',
    pleaseSendId: 'Contactez le support avec votre ID en cas de souci.',
    copyId: 'Copier ID',
    // Landing Page
    landingTitle: 'Studio',
    landingTitleSuffix: 'Photoshoot',
    landingSubtitle: 'Créez des photographies de mode professionnelles et ultra-réalistes avec vos propres photos. Économisez plus de 50 000 CFA sur les shootings pro.',
    launchStudio: 'Lancer le Studio',
    featuresAIModelsTitle: 'Shooting Professionnel',
    featuresAIModelsDesc: 'Téléchargez votre vraie photo et obtenez des résultats studio professionnels instantanément.',
    featuresGarmentsTitle: 'Vêtements Personnalisés',
    featuresGarmentsDesc: 'Décrivez n\'importe quelle tenue et voyez-la drapée parfaitement avec une physique de tissu réaliste.',
    featuresVideoTitle: 'Vidéo 4K',
    featuresVideoDesc: 'Animez vos photos en vidéos cinématographiques 4K époustouflantes avec mouvement de caméra.',
    navHome: 'Accueil',
    navTryOn: 'Essayage Virtuel',
    navPhotoshoot: 'Studio Photoshoot',
    navCreatives: 'Studio Créatif',
    navAccount: 'Compte Utilisateur',
    navInspiration: 'Galerie d\'Inspiration',
    creditsLabel: 'Crédits',
    // Creatives Studio
    creativesTitle: 'Studio Créatif',
    creativesSubtitle: 'Générez des designs publicitaires professionnels et des créations marketing directement à partir de vos entrées.',
    comingSoon: 'Bientôt Disponible',
    adGeneratorPlaceholder: 'Aperçu du Générateur de Pub',
    // Home Landing Page
    homeLiveBadge: 'Studio a6ko est maintenant en ligne',
    homeHeroTitle1: 'Le Moteur Créatif',
    homeHeroTitle2: 'Propulsé par l\'IA',
    homeHeroSubtitle: 'Générez des photos de mode hyper-réalistes, concevez des identités de marque et créez des publicités à fort taux de conversion en quelques secondes.',
    homePhotoshootTitle: 'Studio Photo Virtuel',
    homePhotoshootDesc: 'Téléchargez vos vêtements et générez des photos de mode hyper-réalistes dans divers environnements, éclairages et poses.',
    homeCreativesTitle: 'Studio Créatif Publicitaire',
    homeCreativesDesc: 'Concevez des logos, des présentations, des visuels pour réseaux sociaux et des ressources marketing adaptés à votre identité de marque.',
    homeWhyChooseTitle: 'Pourquoi choisir Studio a6ko ?',
    homeWhyChooseSubtitle: 'Remplacez les agences coûteuses, les longs délais d\'attente et les logiciels complexes par une perfection instantanée générée par l\'IA.',
    homeFeature1Title: 'Ultra Rapide',
    homeFeature1Desc: 'Passez du concept à la ressource finale en quelques secondes. Fini les semaines d\'attente pour les séances photo ou les révisions de design.',
    homeFeature2Title: 'Rentable',
    homeFeature2Desc: 'Éliminez le besoin de séances photo, de photographes, de studios coûteux et d\'agences de création aux tarifs élevés.',
    homeFeature3Title: 'Hyper-Local & Global',
    homeFeature3Desc: 'Générez instantanément des personnes diversifiées et des designs culturellement pertinents adaptés à n\'importe quel marché ou groupe démographique.',
    homeDeepDivePhotoshootTag: 'Séance Photo Virtuelle',
    homeDeepDivePhotoshootTitle1: 'Vos vêtements sur',
    homeDeepDivePhotoshootTitle2: 'des personnes hyper-réalistes',
    homeDeepDivePhotoshootDesc: 'Arrêtez de payer pour du temps de studio coûteux. Téléchargez une photo à plat de vos vêtements et laissez notre IA les draper naturellement sur diverses personnes dans n\'importe quel décor, éclairage ou pose.',
    homeDeepDivePhotoshootList1: 'Téléchargez des photos à plat ou de vêtements',
    homeDeepDivePhotoshootList2: 'Sélectionnez l\'origine ethnique, l\'âge et la morphologie de la personne',
    homeDeepDivePhotoshootList3: 'Choisissez un éclairage de studio ou des environnements extérieurs',
    homeDeepDivePhotoshootList4: 'Générez des images 4K prêtes pour le e-commerce',
    homeDeepDivePhotoshootCTA: 'Essayer le Studio Photo',
    homeDeepDiveCreativesTag: 'Studio Créatif Publicitaire',
    homeDeepDiveCreativesTitle1: 'Générez des',
    homeDeepDiveCreativesTitle2: 'ressources à fort taux de conversion',
    homeDeepDiveCreativesDesc: 'De l\'identité de marque fondamentale au marketing de performance. Adaptez chaque ressource à votre public cible, à votre déclencheur émotionnel et à votre proposition de valeur fondamentale.',
    homeTab1Title: 'Identité de Marque',
    homeTab1Desc: 'Logos, directives et ressources de base.',
    homeTab2Title: 'Marketing Numérique',
    homeTab2Desc: 'Réseaux sociaux, e-mails et publicités web.',
    homeTab3Title: 'Ventes & Présentations',
    homeTab3Desc: 'Présentations et pitch decks.',
    homeDeepDiveCreativesCTA: 'Essayer le Studio Créatif',
    homeFinalCTATitle: 'Prêt à transformer votre marque ?',
    homeFinalCTASubtitle: 'Rejoignez des milliers de créateurs, d\'agences et de marques qui utilisent Studio a6ko pour faire évoluer leur production créative.',
    homeFinalCTAPhotoshoot: 'Démarrer la Séance Photo',
    homeFinalCTACreatives: 'Concevoir des Créations',
    // Creatives Landing Page
    creativesLandingTitle: 'Que devez-vous créer aujourd\'hui ?',
    creativesLandingSubtitle: 'Sélectionnez une catégorie créative ci-dessous pour lancer le studio IA personnalisé.',
    creativesCat1Title: 'Identité de Marque Fondamentale',
    creativesCat2Title: 'Présence Numérique & Marketing',
    creativesCat3Title: 'Impression & Ressources Physiques',
    creativesCat4Title: 'Ventes & Communication',
    creativesCat1Item1: 'Création de Logo',
    creativesCat1Item2: 'Charte Graphique (Style Guide)',
    creativesCat1Item3: 'Ressources de Marque',
    creativesCat2Item1: 'Design de Site Web (UI/UX)',
    creativesCat2Item2: 'Visuels pour Réseaux Sociaux',
    creativesCat2Item3: 'Modèles d\'E-mail Marketing',
    creativesCat2Item4: 'Publicités Numériques',
    creativesCat3Item1: 'Cartes de Visite & Papeterie',
    creativesCat3Item2: 'Design d\'Emballage',
    creativesCat3Item3: 'Brochures & Dépliants',
    creativesCat4Item1: 'Pitch Decks & Présentations',
    creativesCat4Item2: 'Supports de Vente',
    creativesCat4Item3: 'Ressources de sortie musicale',
    creativesCat1Item1Desc: 'Un logo unique et mémorable est la base de la reconnaissance de la marque.',
    creativesCat1Item2Desc: 'Un document garantissant la cohérence des couleurs, des polices et du ton de la marque sur toutes les plateformes.',
    creativesCat1Item3Desc: 'Images sélectionnées, icônes et, si nécessaire, illustrations personnalisées.',
    creativesCat2Item1Desc: 'Un site web réactif qui sert de plaque tournante pour l\'engagement client.',
    creativesCat2Item2Desc: 'Modèles pour les publications, les stories et les bannières afin de maintenir une esthétique cohérente.',
    creativesCat2Item3Desc: 'Mises en page aux couleurs de la marque pour les newsletters et les e-mails promotionnels.',
    creativesCat2Item4Desc: 'Images percutantes pour Google Ads, les publicités sur les réseaux sociaux et les bannières.',
    creativesCat3Item1Desc: 'Des supports de marque professionnels et tangibles pour le réseautage.',
    creativesCat3Item2Desc: 'Crucial pour attirer les clients en rayon.',
    creativesCat3Item3Desc: 'Brochures, dépliants et bannières pour les lieux physiques ou les événements.',
    creativesCat4Item1Desc: 'Des diapositives visuellement attrayantes pour les propositions, les pitchs aux investisseurs ou les réunions clients.',
    creativesCat4Item2Desc: 'Des documents conçus pour rendre les données faciles à comprendre.',
    creativesCat4Item3Desc: 'Ressources pour les sorties musicales.',
    creativesStudioTitle: 'Studio Créatif Publicitaire',
    creativesStudioDesc: 'Générez des publicités visuelles performantes.',
    yourCreativesTitle: 'Vos Créations',
    yourCreativesDesc: 'Remplissez les champs requis à gauche et cliquez sur "Générer la Création" pour voir la magie opérer.',
    generateAdCreative: 'Générer la Création',
    costCredit: 'Coût : {cost} Crédit',
    balance: 'Solde : {credits}',
    verifyingIdentity: 'Vérification de l\'identité...',
    photoReady: 'Photo Prête',
    apiKeyRequiredTitle: 'La Génération de Vidéo Nécessite une Clé API',
    apiKeyRequiredDesc: 'Pour créer des animations, cette application utilise les puissants modèles Veo de Google. Vous devrez sélectionner une clé API Google AI à partir d\'un projet avec facturation activée pour continuer.',
    selectApiKey: 'Sélectionner une Clé API',
    apiKeyDisclaimer: 'Votre clé API est utilisée directement et n\'est pas stockée par cette application. Pour plus d\'informations sur la facturation, veuillez visiter',
    marketingCopy: 'Texte Marketing',
    satisfaction: 'Satisfaction',
    // User Account
    accountTitle: 'Compte Utilisateur',
    directorId: 'ID Directeur',
    availableCredits: 'Crédits Disponibles',
    needHelp: 'Besoin d\'aide ? Contactez le support avec votre ID Directeur.',
    whatsappShareMessage: "Essaie tes modeles gratuitement avec Studio A6ko 📸✨\n",
    loginTitle: 'Connexion au Studio',
    loginSubtitle: 'L\'authentification est requise pour sécuriser votre espace créatif et protéger vos crédits de création.',
    continueWithGoogle: 'Continuer avec Google',
    loginSecurePromise: 'Politique Anti-Farming : Afin de garantir la stabilité des serveurs et d\'assurer une distribution équitable des ressources, nous exigeons des comptes sociaux vérifiés.',
    signOut: 'Se déconnecter',
  },
};