
export const GARMENT_PROMPTS: string[] = [
    "A flowing Ankara maxi dress with chandelier beaded earrings that echo the dress patterns.",
    "A chic off-shoulder kente midi dress paired with oversized gold hoop earrings.",
    "A radiant wax print gown with dangling cowrie shell earrings.",
    "A regal kaftan with gold embroidery, styled with large teardrop pearl earrings.",
    "A fitted mermaid gown in woven kente with geometric brass earrings.",
    "A bohemian ruffle maxi dress paired with long feather earrings.",
    "A playful skater dress in patchwork Ankara with bold triangular wood earrings.",
    "A minimalist slip dress styled with subtle mudcloth prints and thin silver threader earrings.",
    "A dramatic cape gown in velvet wax print, with gemstone chandelier earrings.",
    "A halter-neck wax evening gown with oversized spiral gold earrings.",
    "A flowing Ankara maxi dress with bold geometric prints, paired with gold hoop earrings, stacked bangles, and a matching Ankara clutch.",
    "A sleek kente wrap dress, styled with brass ear cuffs, a woven belt, and a raffia handbag.",
    "A radiant wax print gown with dangling cowrie shell earrings, pearl bracelets, and jeweled sandals.",
    "A regal velvet kaftan embroidered in gold, matched with chandelier pearl earrings, a beaded waist belt, and a jeweled clutch.",
    "A fitted mermaid gown in woven kente with diamond-shaped earrings, crystal bangles, and strappy heels.",
    "A bohemian ruffle maxi dress paired with long feather earrings, stacked wooden bangles, and a raffia tote.",
    "A playful skater dress in patchwork Ankara with triangular wood earrings, ankle boots, and a basket clutch.",
    "A minimalist silk slip dress with subtle mudcloth motifs, paired with thin silver threader earrings, layered chains, and a metallic bag.",
    "A dramatic cape gown in wax print and velvet, styled with gemstone chandelier earrings, a metallic clutch, and velvet sandals.",
    "A halter-neck wax evening gown with oversized spiral earrings, a gold belt, and satin heels.",
    "A balloon-sleeve Ankara midi dress with hammered brass earrings, a beaded necklace, and wedge sandals.",
    "A peplum Ankara gown with crystal drop earrings, stacked rings, and a satin handbag.",
    "A strapless kente gown with oversized hoop earrings, a clutch, and lace-up heels.",
    "A deep V-neck wax print gown styled with beaded tassel earrings, a woven clutch, and metallic bangles.",
    "A layered chiffon dress with subtle batik patterns, styled with pearl stud earrings, a belt, and ankle-strap heels.",
    "A one-shoulder wax gown with spiral silver earrings, stacked cuffs, and a box clutch.",
    "A puff-sleeve Ankara mini dress with cowrie shell earrings, a belt bag, and block heels.",
    "A high-slit mermaid wax print dress styled with chandelier earrings, jeweled sandals, and a velvet shawl.",
    "A wrap-style Ankara dress with tassel earrings, layered bangles, and strappy heels.",
    "A tiered wax print maxi dress with feather earrings, beaded anklets, and raffia sandals.",
    "A lace-overlay gown with kente lining, styled with gold drop earrings, a clutch, and high heels.",
    "A ruffled Ankara gown with geometric brass earrings, stacked bangles, and metallic sandals.",
    "A cowl-neck wax gown paired with diamond studs, layered rings, and a pearl clutch.",
    "A fitted corset dress in Ankara with bold chandelier earrings, ankle boots, and a crossbody bag.",
    "A bubble-hem wax mini dress styled with shell earrings, strappy heels, and a metallic purse.",
    "A velvet mermaid gown with tribal-inspired earrings, crystal cuffs, and platform sandals.",
    "A pleated Ankara gown styled with hoop earrings, a matching scarf, and jeweled flats.",
    "A fishtail kente gown paired with drop pearl earrings, stacked bangles, and satin heels.",
    "A bell-sleeve wax gown with oversized spiral earrings, a beaded clutch, and platform heels.",
    "A dramatic train gown in Ankara fabric, paired with chandelier earrings, metallic sandals, and a jeweled belt.",
    "A sleek kente jumpsuit with sculptural ear cuffs in bronze.",
    "A batik-inspired power suit paired with minimalist hoop studs.",
    "A dashiki-style blazer with cascading chain earrings.",
    "A bold Ankara pantsuit with multicolored beaded tassel earrings.",
    "A structured peplum jacket with hand-painted batik, styled with jade drop earrings.",
    "A cropped blazer with Ankara lining, matched with shell hoop earrings.",
    "A two-piece set with wide-leg trousers and beaded chandelier earrings.",
    "A bell-bottom wax jumpsuit paired with long feathered gold earrings.",
    "A metallic-threaded kente suit with angular geometric earrings.",
    "A denim-Ankara patchwork jumpsuit with oversized hammered brass hoops.",
    "A batik-inspired power suit with wide-leg trousers, styled with angular brass earrings, a bold cuff bracelet, and a crocodile-leather handbag.",
    "A denim-Ankara patchwork jumpsuit styled with large hammered brass hoops, a woven crossbody bag, and platform sandals.",
    "A cropped Ankara blazer with high-waist trousers, paired with beaded tassel earrings, a structured handbag, and bold bangles.",
    "A sleek kente jumpsuit with wide legs, styled with sculptural bronze ear cuffs, layered necklaces, and metallic heels.",
    "A batik power suit with flared trousers, styled with angular earrings, a crocodile handbag, and stilettos.",
    "A tailored dashiki blazer with slim trousers, styled with tassel earrings, a leather tote, and pumps.",
    "A bold Ankara pantsuit paired with chandelier earrings, a belt, and platform sandals.",
    "A cropped wax blazer with matching skirt, styled with dangling crystal earrings, stacked rings, and ankle boots.",
    "A fitted peplum jacket with batik motifs, paired with jade earrings, a clutch, and high heels.",
    "A jumpsuit with bell bottoms, styled with feather earrings, a metallic belt, and wedge sandals.",
    "A two-piece Ankara set with oversized hoop earrings, a satchel, and strappy heels.",
    "A striped wax-print suit paired with beaded drop earrings, bangles, and leather loafers.",
    "A kente corset jumpsuit with gold drop earrings, a clutch, and lace-up heels.",
    "A metallic-threaded kente suit paired with sculptural silver earrings, a structured bag, and heels.",
    "A velvet tuxedo with Ankara lining, styled with pearl studs, a bow belt, and pointed pumps.",
    "A denim-Ankara patchwork jumpsuit styled with hammered brass hoops, a woven tote, and sneakers.",
    "A cropped batik jacket with high-waist trousers, styled with crystal earrings, bangles, and strappy heels.",
    "A wide-leg wax jumpsuit paired with cowrie shell earrings, stacked rings, and beaded sandals.",
    "A belted Ankara utility suit with hoop earrings, a clutch, and ankle boots.",
    "A double-breasted wax suit styled with drop earrings, bangles, and a metallic bag.",
    "A short-sleeve kente jumpsuit with chandelier earrings, a leather tote, and block heels.",
    "A denim jumpsuit with wax print sleeves, styled with spiral earrings, sneakers, and a crossbody bag.",
    "A silk tuxedo gown hybrid with dangling gemstone earrings, stacked cuffs, and satin heels.",
    "A metallic agbada robe with large hammered copper earrings.",
    "A flowing boubou dress paired with moon-shaped pearl studs.",
    "A gele headwrap and gown combo, styled with chandelier crystal earrings.",
    "A short agbada tunic dress paired with dangling cowrie earrings.",
    "A wrapper and blouse set with handwoven basket earrings.",
    "A velvet aso-oke gown with gold filigree drop earrings.",
    "A dashiki tunic styled with large tribal hoop earrings.",
    "An isiagu shirt dress paired with ebony wood earrings.",
    "A kaftan with mudcloth patterns, styled with bone-carved earrings.",
    "A minimalist agbada set paired with sculptural silver ear cuffs.",
    "A modern agbada robe in metallic fabrics, paired with hammered copper earrings, stacked rings, and velvet loafers.",
    "A wrapper and blouse set in wax print, styled with large basket-weave earrings, a beaded clutch, and embroidered sandals.",
    "A velvet aso-oke gown, paired with gold filigree drop earrings, a waist belt, and a crystal handbag.",
    "A flowing boubou with hand-beaded embellishments, styled with pearl stud earrings, a jeweled clutch, and layered bangles.",
    "A kaftan with abstract mudcloth prints, paired with bone-carved earrings, a raffia bag, and leather sandals.",
    "A dashiki tunic with leather leggings, styled with oversized tribal hoop earrings, stacked bangles, and ankle boots.",
    "A modern isiagu shirt dress, paired with ebony wood earrings, a bold leather belt, and a metallic clutch.",
    "A silk Ankara turban and gown set, styled with chandelier crystal earrings, a satin handbag, and gold sandals.",
    "A peplum jacket with painted batik motifs, paired with jade drop earrings, a structured handbag, and stilettos.",
    "A wax print kimono with flowing sleeves, styled with dangling shell earrings, a beaded clutch, and tasseled sandals.",
    "A corset dress in vibrant Ankara, paired with silver spike earrings, layered rings, and a chain clutch.",
    "A metallic agbada robe with hammered copper earrings, velvet sandals, and a woven clutch.",
    "A flowing boubou styled with pearl studs, a jeweled belt, and crystal sandals.",
    "A gele headwrap with matching Ankara gown, paired with chandelier earrings and a clutch.",
    "A short agbada tunic dress with cowrie earrings, bangles, and block heels.",
    "A wrapper and blouse set styled with basket earrings, a raffia clutch, and sandals.",
    "A velvet aso-oke gown with filigree drop earrings, a jeweled clutch, and stilettos.",
    "A dashiki tunic paired with large tribal hoop earrings, leggings, and leather boots.",
    "An isiagu shirt dress styled with ebony wood earrings, a clutch, and strappy heels.",
    "A kaftan with mudcloth patterns, styled with bone-carved earrings, sandals, and a raffia bag.",
    "A minimalist agbada set paired with silver ear cuffs, velvet slippers, and a metallic tote.",
    "A beaded Yoruba-inspired gown with chandelier earrings, bangles, and jeweled sandals.",
    "A Ghanaian kente wrapper styled with spiral earrings, a waist chain, and metallic sandals.",
    "An embroidered Fulani tunic paired with hammered brass earrings, bangles, and ankle boots.",
    "A batik boubou with cowrie shell earrings, raffia sandals, and a woven tote.",
    "A traditional aso-oke dress styled with chandelier earrings, a clutch, and heels.",
    "A Yoruba iro and buba styled with beaded tassel earrings, bangles, and sandals.",
    "A Xhosa-inspired gown with bold geometric earrings, a beaded necklace, and strappy sandals.",
    "A modern agbada dress with chandelier earrings, a beaded clutch, and ankle boots.",
    "A Hausa-inspired wrapper gown styled with pearl earrings, a jeweled bag, and sandals.",
    "A batik kaftan with drop earrings, bangles, and embroidered slippers.",
    "A bomber jacket in Ankara patchwork paired with metallic safety-pin earrings.",
    "A cropped hoodie styled with neon acrylic earrings.",
    "A wax print corset top with distressed jeans and hoop chain earrings.",
    "A streetwear tracksuit paired with angular geometric studs.",
    "A trench coat with Ankara lining and futuristic metallic ear cuffs.",
    "A pleated wax mini skirt with oversized feather earrings.",
    "A varsity jacket with kente panels and leather hoop earrings.",
    "A denim jacket embroidered with tribal motifs, styled with stacked ear piercings.",
    "A wax print bucket hat paired with oversized bamboo earrings.",
    "A futuristic windbreaker with digital African prints and chrome hoop earrings.",
    "A streetwear tracksuit with tribal stripe details, styled with chrome hoop earrings, a fanny pack, and chunky sneakers.",
    "A varsity jacket with kente panels, paired with leather hoop earrings, a mini backpack, and lace-up boots.",
    "A trench coat lined with Ankara prints, styled with futuristic metallic ear cuffs, a silk scarf, and knee-high boots.",
    "A bomber jacket with wax patchwork and leather sleeves, paired with feather earrings, a crossbody bag, and cargo pants.",
    "A cropped hoodie with neon tribal patterns, styled with acrylic earrings, layered chains, and joggers.",
    "A futuristic wax print windbreaker, paired with chrome hoop earrings, mirrored sunglasses, and combat boots.",
    "A bomber jacket in Ankara patchwork paired with metallic hoop earrings, cargo pants, and sneakers.",
    "A cropped hoodie with tribal prints, styled with neon acrylic earrings, joggers, and chunky sneakers.",
    "A wax corset top with jeans, styled with chain earrings, a belt bag, and strappy heels.",
    "A streetwear tracksuit with African stripe details, styled with geometric earrings, sneakers, and a crossbody bag.",
    "A trench coat lined with Ankara fabric, paired with metallic ear cuffs, boots, and a clutch.",
    "A wax pleated mini skirt with feather earrings, an oversized sweater, and ankle boots.",
    "A varsity jacket with kente panels, styled with leather hoop earrings, joggers, and sneakers.",
    "A denim jacket embroidered with tribal motifs, paired with stacked earrings, cargo pants, and boots.",
    "A wax bucket hat styled with bamboo earrings, wide-leg jeans, and sneakers.",
    "A futuristic wax windbreaker, paired with chrome hoop earrings, combat boots, and a backpack.",
    "A cropped Ankara bomber with tassel earrings, joggers, and platform sneakers.",
    "A wax print hoodie styled with spiral earrings, ripped jeans, and a clutch.",
    "A leather jacket with Ankara patches, styled with dangling earrings, boots, and a mini bag.",
    "A wax skater skirt paired with chandelier earrings, a crop top, and sneakers.",
    "A wax puffer jacket styled with metallic earrings, joggers, and trainers.",
    "A trench dress in Ankara paired with hoop earrings, boots, and a belt bag.",
    "A denim-wax overalls styled with drop earrings, sneakers, and a crossbody tote.",
    "A wax varsity sweater styled with geometric earrings, pleated skirt, and flats.",
    "A hooded wax poncho paired with chandelier earrings, sandals, and a woven bag.",
    "A cropped wax jacket styled with oversized earrings, high-waist trousers, and pumps.",
    "A sleek black dress styled with cascading beaded Maasai-inspired earrings.",
    "A metallic Ankara turban paired with oversized gold disc earrings.",
    "A minimalist gown cinched with a bold belt, styled with gemstone chandelier earrings.",
    "A raffia handbag paired with tribal hoop earrings.",
    "A monochrome jumpsuit styled with Ankara fabric earrings.",
    "A silk scarf with mudcloth designs, paired with dangling chain earrings.",
    "A kente clutch styled with twisted brass hoop earrings.",
    "A feathered shawl styled with bold sculptural ear cuffs.",
    "A corset layered over a white shirt, paired with silver spike earrings.",
    "A wax print kimono styled with bold dangling shell earrings.",
    "A regal velvet kaftan embroidered in gold, matched with chandelier pearl earrings, a beaded waist belt, and a jeweled clutch.",
    "A playful Ankara skater dress with patchwork motifs, paired with oversized wooden earrings, a woven raffia handbag, and colorful bangles.",
    "A dramatic cape gown in wax print and velvet, styled with gemstone drop earrings, a metallic choker, and a crystal-studded clutch.",
    "A halter-neck gown in bold African wax patterns, paired with spiral gold earrings, stacked rings, and a satin mini-bag.",
    "A chic off-shoulder midi dress in Ankara fabric, styled with oversized cowrie shell earrings, a beaded belt, and strappy sandals.",
    "A tailored dashiki blazer and slim trousers, paired with brass tassel earrings, a leather handbag, and pointed heels.",
    "A fitted kente mermaid dress with flared hem, styled with diamond-shaped earrings, a crystal bracelet, and a velvet clutch.",
    "A minimalist silk slip dress with subtle mudcloth motifs, paired with thin silver threader earrings, a layered chain necklace, and a metallic mini bag.",
    "A sleek black Ankara gown styled with cascading Maasai-inspired beaded earrings, bangles, and jeweled sandals.",
    "A velvet gown with metallic turban, chandelier earrings, a jeweled clutch, and heels.",
    "A strapless wax gown paired with oversized gold disc earrings, a waist chain, and crystal sandals.",
    "A silk gown styled with dangling cowrie earrings, a raffia handbag, and metallic heels.",
    "A kente gown paired with oversized spiral earrings, a stacked choker, and a jeweled purse.",
    "A chiffon gown styled with gemstone earrings, a metallic clutch, and beaded sandals.",
    "A corset Ankara dress styled with spike earrings, stacked cuffs, and a crossbody bag.",
    "A kimono wax gown paired with dangling shell earrings, raffia heels, and a woven tote.",
    "A satin gown styled with chandelier earrings, a jeweled clutch, and metallic stilettos.",
    "A velvet wax gown with oversized hoop earrings, a beaded belt, and platform heels.",
];
