export const MODEL_PROMPTS: string[] = [
  "An African fashion model with a curvy figure and long braided hair.",
  "A métisse fashion model with a voluptuous shape and sharp, high-fashion features.",
  "An African woman with an hourglass body and a confident, powerful stance.",
  "A métisse model with an athletic build and toned physique.",
  "An African beauty with a pear-shaped figure and elegant posture.",
  "A fashion model with full curves and a chic, modern look.",
  "An African model with a slim-thick body, exuding confidence.",
  "A métisse woman as a fashion icon, with striking features.",
  "An African fashion model with rounded hips and a warm smile.",
  "A métisse model with a voluptuous form and lifelike skin textures.",
  "An African lady with an hourglass silhouette and detailed, glowing skin.",
  "A métisse beauty with a curvy build, perfect for a close-up jewelry shot.",
  "An African fashion model with thick thighs and a strong, stretching pose.",
  "A full-figured métisse model with realistic shadows and a party-ready look.",
  "An African woman with a bodycon-ready figure, walking confidently.",
  "A tall African model with long legs and a runway-ready walk.",
  "A slender métisse beauty with an elegant posture and fine details.",
  "A muscular African woman model with defined abs, in a gym setting.",
  "A plus-size métisse model with confident curves and a lifelike presence.",
  "A petite African fashion model with delicate features, seated gracefully.",
  // New Prompts Inspired by Celebrity Hairstyles
  // Women's Styles
  "An African fashion model with long layered Hollywood waves and a glossy finish.",
  "A métisse fashion model with a textured asymmetrical bob and choppy layers.",
  "An African woman with sculpted box braids styled into a dramatic updo.",
  "A fashion model with sleek center-parted long straight hair.",
  "An African beauty with a modern layered blowout and bouncy movement.",
  "A métisse model with vintage finger waves for an old-Hollywood glamour look.",
  "A confident fashion model with short tapered natural curls.",
  "An elegant model with a high, voluminous ponytail.",
  "A fashion model with a sculpted braided crown for a regal effect.",
  "An African woman with a textured pixie cut and tapered sides.",
  // Men's Styles
  "A male fashion model with a classic undercut and a textured top.",
  "A male model with tousled medium-length waves and a romantic silhouette.",
  "A West African male model with beachy long layers and surfer-style waves.",
  "A male fashion model with a modern textured quiff.",
  "A sophisticated male model with a sculpted short afro with defined edges.",
  "A male model with a shoulder-length lob and slightly layered hair.",
  "A male model with a fade and a curly top.",
  "A West African male model with braided cornrow styles, accessorized with metallic beads.",
  "A male model with a sharp Caesar cut and a defined fringe.",
  "A male fashion model with 70s-inspired floppy waves and a relaxed part."
];
